services:
  server:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
    - "../serve:/var/www/html:ro"
    - "../data:/data:ro"
    # Update this to wherever you want VS Code to mount the folder of your project
    - "..:/workspaces:cached"
    ports:
    - 8080:80
    # Overrides default command so things don't shut down after the process ends
    # command: sleep infinity
